# -----------------------------------------------------
# Configuracao da porta e contexto da aplicacao
# -----------------------------------------------------
server:
  port: 8080
  servlet.context-path: /dio

# --------------------------------------------------------
# configuracao do banco de dados
# --------------------------------------------------------
spring:
  sql.init.mode: always
  datasource:
    url: jdbc:h2:mem:database
    driverClassName: org.h2.Driver
    username: admin
    password:

  # --------------------------------------------------------
  # configuracao do H2
  # --------------------------------------------------------
  h2:
    console:
      enabled: true
      path: /h2-console

  # --------------------------------------------------------
  # configuracoes da JPA
  # --------------------------------------------------------
  jpa:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
    show-sql: true
