INSERT INTO Estado (nome, sigla) VALUES ('Acre', 'AC');
INSERT INTO Estado (nome, sigla) VALUES ('Alagoas', 'AL');
INSERT INTO Estado (nome, sigla) VALUES ('Amazonas', 'AM');
INSERT INTO Estado (nome, sigla) VALUES ('Amapá', 'AP');
INSERT INTO Estado (nome, sigla) VALUES ('Bahia', 'BA');
INSERT INTO Estado (nome, sigla) VALUES ('Ceará', 'CE');
INSERT INTO Estado (nome, sigla) VALUES ('Distrito Federal', 'DF');
INSERT INTO Estado (nome, sigla) VALUES ('Espírito Santo', 'ES');
INSERT INTO Estado (nome, sigla) VALUES ('Goiás', 'GO');
INSERT INTO Estado (nome, sigla) VALUES ('Maranhão', 'MA');
INSERT INTO Estado (nome, sigla) VALUES ('Minas Gerais', 'MG');
INSERT INTO Estado (nome, sigla) VALUES ('Mato Grosso do Sul', 'MS');
INSERT INTO Estado (nome, sigla) VALUES ('Mato Grosso', 'MT');
INSERT INTO Estado (nome, sigla) VALUES ('Pará', 'PA');
INSERT INTO Estado (nome, sigla) VALUES ('Paraíba', 'PB');
INSERT INTO Estado (nome, sigla) VALUES ('Pernambuco', 'PE');
INSERT INTO Estado (nome, sigla) VALUES ('Piauí', 'PI');
INSERT INTO Estado (nome, sigla) VALUES ('Paraná', 'PR');
INSERT INTO Estado (nome, sigla) VALUES ('Rio de Janeiro', 'RJ');
INSERT INTO Estado (nome, sigla) VALUES ('Rio Grande do Norte', 'RN');
INSERT INTO Estado (nome, sigla) VALUES ('Rondônia', 'RO');
INSERT INTO Estado (nome, sigla) VALUES ('Roraima', 'RR');
INSERT INTO Estado (nome, sigla) VALUES ('Rio Grande do Sul', 'RS');
INSERT INTO Estado (nome, sigla) VALUES ('Santa Catarina', 'SC');
INSERT INTO Estado (nome, sigla) VALUES ('Sergipe', 'SE');
INSERT INTO Estado (nome, sigla) VALUES ('São Paulo', 'SP');
INSERT INTO Estado (nome, sigla) VALUES ('Tocantins', 'TO');

INSERT INTO Cidade (nome, uf, capital) VALUES ('Brasília', 'DF', 1);
INSERT INTO Cidade (nome, uf, capital) VALUES ('Goiânia', 'GO', 1);
INSERT INTO Cidade (nome, uf, capital) VALUES ('Salvador', 'BA', 1);
INSERT INTO Cidade (nome, uf, capital) VALUES ('Fortaleza', 'CE', 1);
INSERT INTO Cidade (nome, uf, capital) VALUES ('Curitiba', 'PR', 1);
INSERT INTO Cidade (nome, uf, capital) VALUES ('São Paulo', 'SP', 1);
INSERT INTO Cidade (nome, uf, capital) VALUES ('Rio de Janeiro', 'RJ', 1);
INSERT INTO Cidade (nome, uf, capital) VALUES ('Anápolis', 'GO', 0);
INSERT INTO Cidade (nome, uf, capital) VALUES ('Pouso Alegre', 'MG', 0);
INSERT INTO Cidade (nome, uf, capital) VALUES ('Volta Redonda', 'RJ', 0);
