INSERT INTO Estado (id, nome, sigla) VALUES (1000, 'Acre', 'AC');
INSERT INTO Estado (id, nome, sigla) VALUES (1002, 'Alagoas', 'AL');
INSERT INTO Estado (id, nome, sigla) VALUES (1003, 'Amazonas', 'AM');
INSERT INTO Estado (id, nome, sigla) VALUES (1004, 'Amapá', 'AP');
INSERT INTO Estado (id, nome, sigla) VALUES (1005, 'Bahia', 'BA');
INSERT INTO Estado (id, nome, sigla) VALUES (1006, 'Ceará', 'CE');
INSERT INTO Estado (id, nome, sigla) VALUES (1007, 'Distrito Federal', 'DF');
INSERT INTO Estado (id, nome, sigla) VALUES (1008, 'Espírito Santo', 'ES');
INSERT INTO Estado (id, nome, sigla) VALUES (1009, 'Goiás', 'GO');
INSERT INTO Estado (id, nome, sigla) VALUES (1010, 'Maranhão', 'MA');
INSERT INTO Estado (id, nome, sigla) VALUES (1011, 'Minas Gerais', 'MG');
INSERT INTO Estado (id, nome, sigla) VALUES (1012, 'Mato Grosso do Sul', 'MS');
INSERT INTO Estado (id, nome, sigla) VALUES (1013, 'Mato Grosso', 'MT');
INSERT INTO Estado (id, nome, sigla) VALUES (1014, 'Pará', 'PA');
INSERT INTO Estado (id, nome, sigla) VALUES (1015, 'Paraíba', 'PB');
INSERT INTO Estado (id, nome, sigla) VALUES (1016, 'Pernambuco', 'PE');
INSERT INTO Estado (id, nome, sigla) VALUES (1017, 'Piauí', 'PI');
INSERT INTO Estado (id, nome, sigla) VALUES (1018, 'Paraná', 'PR');
INSERT INTO Estado (id, nome, sigla) VALUES (1019, 'Rio de Janeiro', 'RJ');
INSERT INTO Estado (id, nome, sigla) VALUES (1020, 'Rio Grande do Norte', 'RN');
INSERT INTO Estado (id, nome, sigla) VALUES (1021, 'Rondônia', 'RO');
INSERT INTO Estado (id, nome, sigla) VALUES (1022, 'Roraima', 'RR');
INSERT INTO Estado (id, nome, sigla) VALUES (1023, 'Rio Grande do Sul', 'RS');
INSERT INTO Estado (id, nome, sigla) VALUES (1024, 'Santa Catarina', 'SC');
INSERT INTO Estado (id, nome, sigla) VALUES (1025, 'Sergipe', 'SE');
INSERT INTO Estado (id, nome, sigla) VALUES (1026, 'São Paulo', 'SP');
INSERT INTO Estado (id, nome, sigla) VALUES (1027, 'Tocantins', 'TO');

INSERT INTO Cidade (id, nome, uf, capital, estado_id) VALUES (10000, 'Brasília', 'DF', 1, 1007);
INSERT INTO Cidade (id, nome, uf, capital, estado_id) VALUES (10002, 'Goiânia', 'GO', 1, 1009);
INSERT INTO Cidade (id, nome, uf, capital, estado_id) VALUES (10003, 'Salvador', 'BA', 1, 1005);
INSERT INTO Cidade (id, nome, uf, capital, estado_id) VALUES (10004, 'Fortaleza', 'CE', 1, 1006);
INSERT INTO Cidade (id, nome, uf, capital, estado_id) VALUES (10005, 'Curitiba', 'PR', 1, 1018);
INSERT INTO Cidade (id, nome, uf, capital, estado_id) VALUES (10006, 'São Paulo', 'SP', 1, 1026);
INSERT INTO Cidade (id, nome, uf, capital, estado_id) VALUES (10007, 'Rio de Janeiro', 'RJ', 1, 1019);
INSERT INTO Cidade (id, nome, uf, capital, estado_id) VALUES (10008, 'Anápolis', 'GO', 0, 1009);
INSERT INTO Cidade (id, nome, uf, capital, estado_id) VALUES (10009, 'Pouso Alegre', 'MG', 0, 1011);
INSERT INTO Cidade (id, nome, uf, capital, estado_id) VALUES (10010, 'Volta Redonda', 'RJ', 0, 1019);
